sudo: required

services:
  - docker

install:
  - docker pull matthiasnoback/php_workshop_tools_library_test

script:
  - docker run --rm -v $(pwd):/opt matthiasnoback/php_workshop_tools_library_test
