version: '3'

services:
    base:
        build: docker/base/
        image: matthiasnoback/php_workshop_tools_base

    simple_webserver:
        build: docker/simple_webserver/
        image: matthiasnoback/php_workshop_tools_simple_webserver
        depends_on:
            - base
        volumes:
            - ./docker/test/opt:/opt
        ports:
            - 80:80
        networks:
            - test

    test:
        build: docker/test/
        image: matthiasnoback/php_workshop_tools_test
        depends_on:
            - simple_webserver
        networks:
            - test

networks:
    test:
        driver: bridge
