# example
version: '3'

services:
    website:
        image: matthiasnoback/php_workshop_tools_simple_webserver
        command: /opt/docker/image_test/document_root
        volumes:
            - ./:/opt
            - ${COMPOSER_HOME}:/home/.composer
        ports:
            - 80:8080
        environment:
            COMPOSER_HOME: /home/.composer
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP} remote_log=/dev/stdout"
        user: ${HOST_UID}:${HOST_GID}
