version: '3'

services:
    base:
        build: docker/base/
        image: matthiasnoback/php_workshop_tools_base

    simple_webserver:
        build: docker/simple_webserver/
        image: matthiasnoback/php_workshop_tools_simple_webserver
        depends_on:
            - base
        volumes:
            - ./:/opt
        command: /opt/docker/image_test/opt/web
        ports:
            - 80:80
        networks:
            - test

    image_test:
        build: docker/image_test/
        image: matthiasnoback/php_workshop_tools_image_test
        depends_on:
            - simple_webserver
        networks:
            - test

    library_test:
        build: docker/library_test/
        image: matthiasnoback/php_workshop_tools_library_test
        volumes:
            - ./:/opt

networks:
    test:
        driver: bridge
